Repository globocom/huskyCI-dashboard, pull requests merged in 2019-10, with the labels that each got.

#17 Add check for author array length.
  src/components/Dashboard.js
Labels: fix

#19 dashboard.js|STYLE: fix y-axis minimum to 0
  src/components/Dashboard.js
Labels: feature

#28 [FIX]: added double quotes in .eslintrc
  .eslintrc
Labels: fix

#39 Add prettier
  .eslintrc
  package.json
  src/App.js
  src/App.test.js
  src/components/Dashboard.js
  src/components/SnackComponent.js
  src/index.js
  src/serviceWorker.js
  yarn.lock
Labels: feature

#40 Fix LICENSE link in README.md
  README.md
Labels: docs

#37 Add editorconfig
  .editorconfig
Labels: feature

#35 Update dependencies
  package.json
  yarn.lock
Labels: fix

#38 Components code refactoring
  src/components/Dashboard.js
  src/components/Graph.js
  src/components/Metric.js
Labels: refact

#34 Add responsive TopBar component
  src/App.js
  src/components/TopBar.css
  src/components/TopBar.js
  src/logo.png
Labels: feature

#32 Login page
  package.json
  src/App.js
  src/components/LoginButton.js
  src/pages/Dashboard.js
  src/pages/Login.js
  src/routes.js
Labels: feature

#49 Adjust some hacktoberfest issues
  README.md
  logo-README.png
  src/components/TopBar.js
  src/pages/Dashboard.js
  src/pages/Login.js
  yarn.lock
Labels: fix

#41 Tests: Fixed canvas dependency
  package.json
  src/App.test.js
  yarn.lock
Labels: fix

#51 Add history graph
  src/App.css
  src/components/Dashboard.js
  src/components/Graph.js
Labels: feature

#53 Adjust new images and docs
  Makefile
  README.md
  charts.png
  generate-local-env.sh
  public/index.html
Labels: docs

#54 Add today parameter as default routes
  src/components/Dashboard.js
Labels: refact
