Repository globocom/huskyCI-dashboard, pull requests merged in 2019-09, with the labels that each got.

#2 Add circleCI configuration
  .circleci/config.yml
  Makefile
  package.json
Labels: enhancement

#5 Add build stage into circleCI and build container instructions into Makefile
  .circleci/config.yml
  Dockerfile
  Makefile
Labels: enhancement

#6 Add env var needed to run FE
  .dockerignore
  Dockerfile
Labels: enhancement

#8 Code design improvements
  .eslintignore
  .eslintrc
  .gitignore
  README.md
  package.json
  src/App.js
  src/components/Dashboard.js
  yarn.lock
Labels: enhancement

#9 Fix package.json and add build into ignore
  .gitignore
  package.json
Labels: bug

#10 Add huskyCI dashboard logo as project title and tags
  README.md
  charts.png
  fe.png
  src/logo.png
Labels: documentation, enhancement

#11 Upgrade handlebars dependency
  package.json
  yarn.lock
Labels: enhancement
